blog/config/routes.rb
Blog::Application.routes.draw do
  root :to => "articles#index"
  
  resources :articles do
    resources :comments
    get "test", :on => :member
  end

  resources :users

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
   validates :title, :presence => true
   validates :body, :presence => true
   
   belongs_to :user
   has_and_belongs_to_many :categories
   has_many :comments
   
   scope :published, where("articles.published_at IS NOT NULL")
   scope :draft, where("articles.published_at IS NULL")
   scope :recent, lambda{ published.where("articles.published_at > ?", 1.week.ago.to_date) }
   scope :where_title, lambda{ |term| where("articles.title LIKE ?", "%#{term}%") }
   
   def long_title
     "#{title} - #{published_at}"
   end
   
   def published?
     published_at.present?
   end
end

blog/app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
  
  default_scope order('categories.name')
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  validates :name, :email, :body, :presence => true
  validate :article_should_be_published
  
  def article_should_be_published
    errors.add(:article_id, "is not published yet") if article && !article.published?
  end
end

blog/app/models/comment_observer.rb
class CommentObserver < ActiveRecord::Observer
    def after_create(comment)
      puts "We will notify the user in Chapter 9"
    end
end

blog/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

blog/app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  
  validates :email, :uniqueness => true, :length => {:within => 5..50}, :format => {:with => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i}
  validates :password, :confirmation => true, :length => {:within => 4..8}, :presence => true, :if => :password_required?
  
  has_one :profile
  has_many :articles, :order => 'published_at DESC, title ASC', :dependent => :nullify
  has_many :replies, :through => :articles, :source => :comments
  
  before_save :encrypt_new_password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
  
  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end
    
    def password_required?
      hashed_password.blank? || password.present?
    end
    
    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
  def test
    @article = Article.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end
  
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_filter :load_article
  
  def create
    comment = Comment.new(params[:comment])
    comment.article = Article.find(params[:article_id])
    if comment.save
      redirect_to comment.article, :notice => 'Thanks for your comment'
    else
      redirect_to comment.article, :alert => 'Unable to add comment'
    end
  end
  
  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to @article, :notice => 'Comment deleted'
  end
  
  #private
  #  def load_article
  #    @article = Article.find(params[:article_id])
  #  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to articles_path, :notice => "User successfully added."
     else
       render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:id])
      redirect_to articles_path, :notice => "User updated successfully."
    else
      render :action => 'edit'
    end
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/articles/_article.html.erb
<%= div_for article do %>
	<h3>
		<%= link_to article.title, article %>
		<span class="actions">
			<%= link_to "Edit", edit_article_path(article) %>
			<%= link_to "Delete", article, :confirm => 'Are you sure you want to delete this article?', :method => :delete %>
		</span>
	</h3>
	<%= article.body %>
<% end %>

blog/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :excerpt %><br />
    <%= f.text_field :excerpt %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Excerpt</th>
    <th>Body</th>
    <th>Published at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.location %></td>
    <td><%= article.excerpt %></td>
    <td><%= article.body %></td>
    <td><%= article.published_at %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

blog/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<%= render @article %>

<h3>Comments</h3>

<div id="comments">
	<%= render @article.comments %>
</div>

<%= render :file => 'comments/new' %>

blog/app/views/articles/test.html.erb
<%= @article.to_yaml %>

blog/app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<h3>
		<%= comment.name %> &lt;, <%= comment.email %>&gt; said:
		<span class="actions">
			<%= link_to "Delete", [@article, comment], :comfirm => "Are you sure?", :method => :delete %>
		</span>
	</h3>
	<%= comment.body %>
<% end %>

blog/app/views/comments/new.html.erb
<%= form_for :comment, :url => article_comments_path(@article) do |f| %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</div>
	<div class="actions">
		<%= f.submit 'Add' %>
	</div>
<% end %>

blog/app/views/layouts/application.html.erb
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	
<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>

<%= yield %>

</body>
</html>

blog/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>